### ISSUE TITLE
add new method to show all vid.cantidad group by TipoVid

### ISSUE THREAD

**Issue by Japoivvb** [dinanli2002/Hibernate-#4]
1. after current showAllCampos() create a new method showCantidadVidByTipo()

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by dinanli2002** [comment]
#4 
<img width="478" alt="Screenshot 2024-03-15 at 13 06 52" src="https://github.com/dinanli2002/Hibernate-/assets/135025231/4639f86e-90e8-4fb5-ae71-ab1e6087d1de">

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
