### ISSUE TITLE
add new field nombre to campo model 

### ISSUE THREAD

**Issue by Japoivvb** [dinanli2002/Hibernate-#5]
1. add nombre attribute to campo model and verify everything is working again

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by dinanli2002** [comment]
#5
<img width="342" alt="Screenshot 2024-03-29 at 19 20 55" src="https://github.com/dinanli2002/Hibernate-/assets/135025231/448e15c8-cc23-4535-bde2-9b7dee8465f5">

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
