### ISSUE TITLE
migrate application from SQL database to NoSQL database

### ISSUE THREAD

**Issue by Japoivvb** [dinanli2002/Hibernate-#6]
1. modify application to use only mongoDB, remove Hibernate(MySQL) sentence once everything is working

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot(from each collection) in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by dinanli2002** [comment]
<img width="1169" alt="Screenshot 2024-05-05 at 22 14 22" src="https://github.com/dinanli2002/Hibernate-/assets/135025231/f402f2cd-e72d-4354-9f49-3adcd60c61db">
<img width="1155" alt="Screenshot 2024-05-05 at 22 14 45" src="https://github.com/dinanli2002/Hibernate-/assets/135025231/e3cd7821-6d77-48ed-8947-1b1cfed292d2">
<img width="1139" alt="Screenshot 2024-05-05 at 22 15 02" src="https://github.com/dinanli2002/Hibernate-/assets/135025231/de8db9d2-f5a2-481e-91f7-827bce45c28d">
<img width="1153" alt="Screenshot 2024-05-05 at 22 15 16" src="https://github.com/dinanli2002/Hibernate-/assets/135025231/ffd646b1-cbfe-4a34-bffd-15977744b422">
<img width="1156" alt="Screenshot 2024-05-05 at 22 15 34" src="https://github.com/dinanli2002/Hibernate-/assets/135025231/62b0662e-0adf-4de9-b613-77cbd8cd28eb">
<img width="1143" alt="Screenshot 2024-05-05 at 22 16 01" src="https://github.com/dinanli2002/Hibernate-/assets/135025231/4308da36-9f5c-4991-88e3-0b5c57b9cd0d">

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
good job dinan
